model:
    arch: LearnWho2Com
    agent_num: 5
    shared_policy: True
    shared_img_encoder: 'only_normal_agents'
    attention: 'general'
    sparse: False
    query: True
    query_size: 8
    key_size: 1024
    enc_backbone: resnet_encoder
    dec_backbone: simple_decoder
    feat_squeezer: -1
    feat_channel: 512
    multiple_output: False
data:
    dataset: airsim
    train_split: train
    val_split: val
    test_split: test
    img_rows: 512
    img_cols: 512
    path: /data/airsim-srms-noise-data
    noisy_type: None 
    target_view: 'target'
    commun_label: 'when2com'
training:
    train_iters: 50000
    batch_size: 8
    val_interval: 250
    n_workers: 8
    print_interval: 25
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: None

