model:
    arch: Single_agent
    shuffle_features: None
    agent_num: 5
    enc_backbone: resnet_encoder
    dec_backbone: simple_decoder
    feat_squeezer: -1
    feat_channel: 512
    multiple_output: True
data:
    dataset: airsim
    train_split: train
    val_split: val
    test_split: test
    img_rows: 512
    img_cols: 512
    path: /data/airsim-mrmps-noise-data
    noisy_type: None 
    target_view: 'DroneNP'
training:
    train_iters: 50000
    batch_size: 8
    val_interval: 250
    n_workers: 8
    print_interval: 25
    optimizer:
        name: 'adam'
        lr: 1.0e-5
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: None

# 这个是下限